datasource.driver-class-name=org.postgresql.Driver
datasource.url=jdbc:postgresql://localhost:5432/postgres
datasource.username=postgres
datasource.password=***********

#10 min
codinggame.scheduled.resource=300000

codinggame.base.rate.limit=1000 
