spring.application.name=3026-backend

#HDatabase
spring.datasource.driver-class-name=${datasource.driver-class-name}
spring.datasource.url=${datasource.url}
spring.datasource.username=${datasource.username}
spring.datasource.password=${datasource.password}
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/create_schema.sql

codinggame.scheduled.resource=${codinggame.scheduled.resource}
codinggame.base.rate.limit=${codinggame.base.rate.limit}

codinggame.request.rate.limit.per.minute=5

codinggame.gameplay.default.resource.quotient=${codinggame.gameplay.default.resource.quotient}
codinggame.gameplay.default.money=${codinggame.gameplay.default.money}

server.port=8443
server.ssl.enabled=false
server.ssl.key-store=classpath:keystore/keystore.p12
server.ssl.key-store-password=3026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

#Signupcode
admin.secret.key=admin3026
admin.account.creation.secret.code=key

#Configuration Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email@gmail.com
spring.mail.password=**********
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Jackson properties
spring.jackson.default-property-inclusion=non_null

# Broker
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5671
spring.rabbitmq.username=user
spring.rabbitmq.password=*****************
spring.rabbitmq.virtual-host=/
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.connection-timeout=5000

exchange.main.name=test
