create table cell (x integer not null, y integer not null, zone integer not null, id varchar(255) not null, island_id varchar(255), type enum ('MOUNTAIN','ROCKS','SAND','SEA'), primary key (id));
create table cell_state (cell_id varchar(255), id varchar(255) not null, ship_id varchar(255), state_enum enum ('KNOWN','VISITED'), primary key (id));
create table discovered_islands (island_id varchar(255) not null, player_id varchar(255) not null, discovered_at timestamp(6), islandState enum ('KNOWN, DISCOVERED'));
create table tax (id varchar(255) not null, player_id varchar(255) not null, type enum ('RESCUE', 'CHEAT'), state enum ('DUE', 'PAID'), amount integer, createdAt timestamp, duration integer, primary key (id));
create table error (code integer not null, status integer not null, description varchar(255), id varchar(255) not null, title varchar(255), type varchar(255), primary key (id));
create table island (bonus_quotient float(53) not null, id varchar(255) not null, name varchar(255), primary key (id));
create table offre (price_per_resource float(24) not null, quantity_in integer not null, id varchar(255) not null, player_id varchar(255), resource_type_in enum ('BOISIUM','CHARBONIUM','FERONIUM'), resource_type_out enum ('BOISIUM','CHARBONIUM','FERONIUM'), primary key (id));
create table player (quotient integer not null, color varchar(255), discord_key varchar(255), id varchar(255) not null, island_id varchar(255) unique, name varchar(255), ship_id varchar(255) unique, primary key (id));
create table player_friends (friend_id varchar(255) not null, player_id varchar(255) not null);
create table position_history (created_at timestamp(6), cell_id varchar(255), id varchar(255) not null, ship_id varchar(255), primary key (id));
create table resource (quantity integer not null, max_quantity integer not null, id varchar(255) not null, player_id varchar(255), type enum ('BOISIUM','CHARBONIUM','FERONIUM'), primary key (id));
create table ship (available_move integer not null, last_move_at timestamp(6), cell_id varchar(255), id varchar(255) not null, ship_level_id varchar(255), primary key (id));
create table ship_level (max_movement integer not null, speed integer not null, visibility_range integer not null, resources_requirements varchar(255) not null, id varchar(255) not null, name varchar(255), primary key (id));
alter table if exists cell add constraint FK7bb3vyqfoji5tmoup8qmksd17 foreign key (island_id) references island;
alter table if exists cell_state add constraint FK8iktk16p7buqpt179fd26p593 foreign key (cell_id) references cell;
alter table if exists cell_state add constraint FKrr7y91bg1rf8cpl3mrkn18h7f foreign key (ship_id) references ship;
alter table if exists discovered_islands add constraint FK63k0ix0102dueavr3lll1ptm9 foreign key (island_id) references island;
alter table if exists discovered_islands add constraint FKmsr94whonn5adblndgmbdi3xx foreign key (player_id) references player;
alter table if exists offre add constraint FK8qgv6gs4oamo6m43m1ck1sgay foreign key (player_id) references player;
alter table if exists player add constraint FK1s8h2eta50f0p55s5rvi48i5d foreign key (island_id) references island;
alter table if exists player add constraint FKby5bnv486tu4aqqcvi5577wfm foreign key (ship_id) references ship;
alter table if exists player_friends add constraint FKey3i7pfpx4ujvriyldmg3bank foreign key (friend_id) references player;
alter table if exists player_friends add constraint FK68jyytqxun1fb2u8hi2vufnr5 foreign key (player_id) references player;
alter table if exists position_history add constraint FKfeafpmhcbelrfo5hover87tvy foreign key (cell_id) references cell;
alter table if exists position_history add constraint FKokshpvfw42kyisq8xqwfaxh61 foreign key (ship_id) references ship;
alter table if exists resource add constraint FKdnwdujc4earahxb00j3fv2u63 foreign key (player_id) references player;
alter table if exists ship add constraint FKopffwd3eym04c45y5u34md4lt foreign key (cell_id) references cell;
alter table if exists ship add constraint FKhj3hytytv86xhdk6e78eat6s9 foreign key (ship_level_id) references ship_level;
alter table if exists tax add constraint FK9z8k1wq3lmx7v2a4t0n5c6yb foreign key (player_id) references player;
