package fr.mma.df.codinggame.api.core.exception

enum class ExceptionCodeEnum {
    TECHNICAL_ERROR,
    NOT_FOUND,
    NICE_TRY,
    PAS_CA_ZINEDINE_PAS_AUJOURDHUI_PAS_MAINTENANT_PAS_APRES_TOUT_CE_QUE_TU_AS_FAIT,
    GAME_OVER_INSERT_COINS,
    DELIVERY_IN_PROGRESS,
    EXISTING,
    FORBIDDEN,
    TOO_FAST_TOO_FURIOUS,
    NO_USER_PROVIDED,
    TOO_POOR,
    SHIP_IN_DISTRESS,
    THANKS_BUT_NO_THANKS,
    NAME_ALREADY_USED,
    VOUS_NE_PASSEREZ_PAS,
    TU_NES_PAS_L_ELU_ANAKIN,
    MISSION_IMPOSSIBLE,
    INVALID
}